export const T = {
  en: {
    appName: "Flowgistik PackTrack",
    /* auth */
    login: "Packer Login",
    loginButton: "Login",
    enterPin: "Enter your PIN",
    startShift: "Start Shift",
    invalidPin: "Invalid PIN. Try again.",
    demoPins: "Demo PINs: 1111 (Packer) · 999999 (Supervisor)",
    /* station setup */
    stationSetupTitle: "Station Setup",
    stationSetupSub: "Name this device once — never again",
    stationNameLabel: "Station Name",
    stationNamePH: "e.g. STATION-A",
    saveStation: "Save Station Name",
    stationRequired: "Please enter a station name.",
    stationBadge: "Station",
    /* status */
    status: "Status",
    idle: "IDLE",
    packing: "PACKING",
    onBreak: "ON BREAK",
    onHold: "ON HOLD",
    /* packer ui */
    scanBin: "Scan BIN ID to start",
    scanOrder: "Scan ORDER LABEL to finish",
    scanBinPH: "Scan Bin ID...",
    scanOrderPH: "Scan Order Label...",
    step1: "Pick up a bin and scan its ID to start packing.",
    step2: "Pack items, then scan the ORDER LABEL to complete.",
    startBreak: "Start Break",
    endBreak: "End Break",
    endShift: "End Shift",
    signOut: "Sign Out",
    holdPause: "Hold / Pause",
    resumePacking: "Resume Packing",
    cancelOrder: "Cancel Order",
    selectHoldReason: "Select Hold Reason",
    confirmHold: "Confirm Hold",
    ordersToday: "Orders Today",
    avgTime: "Avg Time",
    ordersHr: "Orders / Hr",
    elapsedTime: "Elapsed",
    breakTime: "Break",
    ordersPacked: "Order Packed!",
    cancel: "Cancel",
    approve: "Approve",
    shiftEnded: "Shift Ended",
    enterSuperPin: "Enter Supervisor PIN to confirm.",
    /* consumables */
    requestConsumables: "Consumable",
    selectConsumableType: "Press a button to record usage",
    consumableRequested: "✓ Usage recorded!",
    consumableMonitor: "Consumable Usage Log",
    pendingRequests: "All Logs",
    fulfilledRequests: "Summary",
    markFulfilled: "Recorded",
    noActiveRequests: "No usage recorded yet",
    allClear: "No usage recorded yet",
    stationLabel: "Station",
    requestedAt: "Requested",
    /* help */
    callSupervisor: "Call Supervisor",
    helpRequested: "Help Requested!",
    helpResolved: "Resolved",
    activeHelpAlerts: "Active Help Alerts",
    noHelpRequests: "No active help requests",
    /* dashboard */
    supervisorDashboard: "Supervisor Dashboard",
    adminDashboard: "Admin Dashboard",
    leaderboard: "Live Leaderboard",
    topPackers: "Top 5 Packers",
    usageLedger: "Usage Ledger",
    predictiveStock: "Predictive Stock",
    hoursRemaining: "Hours Remaining",
    usageRate: "Usage Rate",
    depletionEst: "Depletion Est.",
    liveTab: "Consumables",
    stationsTab: "Live Station",
    overviewTab: "Overview",
    usersTab: "Users",
    settingsTab: "Settings",
    analyticsTab: "Analytics",
    activeStations: "Active Stations",
    inactiveStations: "Inactive Stations",
    noActiveSessions: "No active sessions right now.",
    /* settings */
    editStationName: "Edit Station Name",
    stationNameUpdated: "Station name updated!",
    successful: "Successful!",
    resetStationDesc: "Changing the station name will update all future logs from this device.",
    toggleConsumables: "Show Consumable Section",
    toggleConsumablesDesc: "Enable or disable the consumable usage recording section for packers.",
    addConsumable: "Add Consumable Type",
    customColor: "Custom Hex Color",
    consumableNamePH: "e.g. TAPE-RED",
    deleteConsumable: "Delete",
    confirmDelete: "Are you sure you want to delete this consumable type?",
    stockLabel: "Current Stock",
    minStockLabel: "Min. Threshold",
    lowStockAlert: "Low Stock Alert!",
    usageAnalytics: "Usage Analytics",
    mostUsedConsumables: "Most Used Consumables",
    kanbanColor: "Kanban Light Color",
    kanbanStatus: "Kanban Status",
    openKanban: "Open Kanban Display",
    activeLabel: "Active",
    completedLabel: "Completed",
    packersLabel: "Packers",
    packerCol: "Packer",
    ordersCol: "Orders",
    avgCol: "Avg Time",
    noDataYet: "No completed orders today yet.",
    /* analytics */
    selectDate: "Select Date",
    selectMonth: "Select Month",
    selectYear: "Select Year",
    dailyAnalytics: "Daily Analytics",
    weeklyAnalytics: "Weekly Analytics",
    monthlyAnalytics: "Monthly Analytics",
    totalOrders: "Total Orders",
    totalPackers: "Total Packers",
    packerProductivity: "Productivity",
    totalConsumables: "Total Consumables",
    performanceByPacker: "Performance by Packer",
    usageByType: "Usage by Type",
    exportCSV: "Export CSV",
    packerDetailView: "Packer Detail View",
    ordersPackedLabel: "Orders Packed",
    ordersPerHour: "Orders / Hour",
    avgCycleTime: "Avg Cycle Time",
    medianP90: "Median / P90",
    shiftStart: "Shift Start",
    shiftEnd: "Shift End",
    totalActiveTime: "Total Active Time",
    totalBreakTime: "Total Break Time",
    totalIdleTime: "Total Idle Time",
    idleTime: "Idle Time",
    currentStatus: "Current Status",
    sessionHistory: "Session History",
    orderIdCol: "Order ID",
    binIdCol: "Bin ID",
    startTimeCol: "Start Time",
    cycleTimeCol: "Cycle Time",
    statusCol: "Status",
    notesCol: "Notes",
    noSessionsFound: "No sessions found for this period.",
    allStatus: "All Status",
    ongoing: "Ongoing",
    /* user management */
    addUser: "Add New User",
    fullNameLabel: "Full Name",
    fullNamePH: "e.g. Budi Santoso",
    roleLabel: "Role",
    pinLabel: "PIN (4-6 digits)",
    confirmPinLabel: "Confirm PIN",
    packerRole: "Packer",
    supervisorRole: "Supervisor",
    userAdded: "User added successfully!",
    pinExists: "PIN already in use.",
    nameRequired: "Name is required.",
    pinFourDigits: "PIN must be 4-6 digits.",
    pinMismatch: "PINs do not match.",
    existingUsers: "Existing Users",
    noUsersYet: "No custom users yet.",
    searchUserPH: "Search by name or PIN...",
    deleteUser: "Delete User",
    deactivateUser: "Deactivate",
    activateUser: "Activate",
    confirmDeleteUser: "Are you sure you want to delete this user?",
    changePin: "Change PIN",
    savePin: "Save PIN",
    /* misc */
    language: "Bahasa Indonesia",
    greatJob: "Great job!",
    back: "Back",
    DAMAGED_ITEM: "Damaged Item",
    MISSING_ITEM: "Missing Item",
    REPRINT_LABEL: "Reprint Label",
    CUSTOMER_REQUEST: "Customer Request",
    SPLIT_SHIPMENT: "Split Shipment",
    OUT_OF_CONSUMABLES: "Out of Consumables",
    ORDER_PROBLEM: "Order Problem",
    OTHER: "Other",
    BOX_SMALL: "Box – Small",
    BOX_MEDIUM: "Box – Medium",
    BOX_LARGE: "Box – Large",
    BUBBLE_WRAP: "Bubble Wrap",
    TAPE: "Tape",
    PLASTIC_BAG: "Plastic Bag",
    CONSUMABLE_OTHER: "Other",
  },
  id: {
    appName: "Flowgistik Packer",
    /* auth */
    login: "Login Packer",
    loginButton: "Masuk",
    enterPin: "Masukkan PIN Anda",
    startShift: "Mulai Shift",
    invalidPin: "PIN salah. Coba lagi.",
    demoPins: "PIN Demo: 1111 (Packer) · 999999 (Supervisor)",
    /* station setup */
    stationSetupTitle: "Setup Stasiun",
    stationSetupSub: "Beri nama perangkat ini sekali — selamanya",
    stationNameLabel: "Nama Stasiun",
    stationNamePH: "mis. STASIUN-A",
    saveStation: "Simpan Nama Stasiun",
    stationRequired: "Masukkan nama stasiun.",
    stationBadge: "Stasiun",
    /* status */
    status: "Status",
    idle: "IDLE",
    packing: "PACKING",
    onBreak: "ISTIRAHAT",
    onHold: "DITAHAN",
    /* packer ui */
    scanBin: "Scan ID BIN untuk mulai",
    scanOrder: "Scan LABEL ORDER untuk selesai",
    scanBinPH: "Scan ID Bin...",
    scanOrderPH: "Scan Label Order...",
    step1: "Ambil bin dan scan ID-nya untuk mulai packing.",
    step2: "Kemas barang, lalu scan LABEL ORDER untuk selesai.",
    startBreak: "Mulai Istirahat",
    endBreak: "Selesai Istirahat",
    endShift: "Akhiri Shift",
    signOut: "Keluar",
    holdPause: "Tahan / Jeda",
    resumePacking: "Lanjut Packing",
    cancelOrder: "Batalkan Order",
    selectHoldReason: "Pilih Alasan Tahan",
    confirmHold: "Konfirmasi Tahan",
    ordersToday: "Order Hari Ini",
    avgTime: "Rata-rata",
    ordersHr: "Order / Jam",
    elapsedTime: "Waktu",
    breakTime: "Istirahat",
    ordersPacked: "Order Dikemas!",
    cancel: "Batal",
    approve: "Setujui",
    shiftEnded: "Shift Berakhir",
    enterSuperPin: "Masukkan PIN Supervisor untuk konfirmasi.",
    /* consumables */
    requestConsumables: "Bahan Kemas",
    selectConsumableType: "Tekan tombol untuk mencatat penggunaan",
    consumableRequested: "✓ Penggunaan dicatat!",
    consumableMonitor: "Log Penggunaan Bahan Kemas",
    pendingRequests: "Semua Log",
    fulfilledRequests: "Ringkasan",
    markFulfilled: "Tercatat",
    noActiveRequests: "Belum ada penggunaan",
    allClear: "Belum ada penggunaan",
    stationLabel: "Stasiun",
    requestedAt: "Diminta",
    /* help */
    callSupervisor: "Panggil Supervisor",
    helpRequested: "Bantuan Diminta!",
    helpResolved: "Selesai",
    activeHelpAlerts: "Peringatan Bantuan Aktif",
    noHelpRequests: "Tidak ada permintaan bantuan aktif",
    /* dashboard */
    supervisorDashboard: "Dashboard Supervisor",
    adminDashboard: "Dashboard Admin",
    leaderboard: "Papan Peringkat",
    topPackers: "Top 5 Packer",
    usageLedger: "Buku Besar Penggunaan",
    predictiveStock: "Prediksi Stok",
    hoursRemaining: "Jam Tersisa",
    usageRate: "Tingkat Penggunaan",
    depletionEst: "Estimasi Habis",
    liveTab: "Bahan Kemas",
    stationsTab: "Stasiun Live",
    overviewTab: "Overview",
    usersTab: "Pengguna",
    settingsTab: "Pengaturan",
    analyticsTab: "Analitik",
    activeStations: "Stasiun Aktif",
    inactiveStations: "Stasiun Tidak Aktif",
    noActiveSessions: "Tidak ada sesi aktif saat ini.",
    successful: "Berhasil!",
    /* settings */
    toggleConsumables: "Tampilkan Bagian Bahan Kemas",
    toggleConsumablesDesc: "Aktifkan atau nonaktifkan bagian pencatatan penggunaan bahan kemas untuk packer.",
    addConsumable: "Tambah Jenis Bahan Kemas",
    customColor: "Warna Hex Kustom",
    consumableNamePH: "mis. LAKBAN-MERAH",
    deleteConsumable: "Hapus",
    confirmDelete: "Apakah Anda yakin ingin menghapus jenis bahan kemas ini?",
    stockLabel: "Stok Saat Ini",
    minStockLabel: "Ambang Batas Min.",
    lowStockAlert: "Peringatan Stok Rendah!",
    usageAnalytics: "Analitik Penggunaan",
    mostUsedConsumables: "Bahan Kemas Paling Banyak Digunakan",
    kanbanColor: "Warna Lampu Kanban",
    kanbanStatus: "Status Kanban",
    openKanban: "Buka Tampilan Kanban",
    activeLabel: "Aktif",
    completedLabel: "Selesai",
    packersLabel: "Packer",
    packerCol: "Packer",
    ordersCol: "Order",
    avgCol: "Rata-rata",
    noDataYet: "Belum ada order selesai hari ini.",
    /* analytics */
    selectDate: "Pilih Tanggal",
    selectMonth: "Pilih Bulan",
    selectYear: "Pilih Tahun",
    dailyAnalytics: "Analitik Harian",
    weeklyAnalytics: "Analitik Mingguan",
    monthlyAnalytics: "Analitik Bulanan",
    totalOrders: "Total Order",
    totalPackers: "Total Packer",
    packerProductivity: "Produktivitas",
    totalConsumables: "Total Bahan Kemas",
    performanceByPacker: "Performa per Packer",
    usageByType: "Penggunaan per Jenis",
    exportCSV: "Ekspor CSV",
    packerDetailView: "Tampilan Detail Packer",
    ordersPackedLabel: "Order Dikemas",
    ordersPerHour: "Order / Jam",
    avgCycleTime: "Rata-rata Waktu Siklus",
    medianP90: "Median / P90",
    shiftStart: "Mulai Shift",
    shiftEnd: "Selesai Shift",
    totalActiveTime: "Total Waktu Aktif",
    totalBreakTime: "Total Waktu Istirahat",
    totalIdleTime: "Total Waktu Menganggur",
    idleTime: "Waktu Idle",
    currentStatus: "Status Saat Ini",
    sessionHistory: "Riwayat Sesi",
    orderIdCol: "ID Order",
    binIdCol: "ID Bin",
    startTimeCol: "Waktu Mulai",
    cycleTimeCol: "Waktu Siklus",
    statusCol: "Status",
    notesCol: "Catatan",
    noSessionsFound: "Tidak ada sesi ditemukan untuk periode ini.",
    allStatus: "Semua Status",
    ongoing: "Berjalan",
    /* user management */
    addUser: "Tambah Pengguna",
    fullNameLabel: "Nama Lengkap",
    fullNamePH: "mis. Budi Santoso",
    roleLabel: "Role",
    pinLabel: "PIN (4-6 digit)",
    confirmPinLabel: "Konfirmasi PIN",
    packerRole: "Packer",
    supervisorRole: "Supervisor",
    userAdded: "Pengguna berhasil ditambahkan!",
    pinExists: "PIN sudah digunakan.",
    nameRequired: "Nama wajib diisi.",
    pinFourDigits: "PIN harus 4-6 digit.",
    pinMismatch: "PIN tidak cocok.",
    existingUsers: "Pengguna Terdaftar",
    noUsersYet: "Belum ada pengguna kustom.",
    searchUserPH: "Cari berdasarkan nama atau PIN...",
    deleteUser: "Hapus Pengguna",
    deactivateUser: "Nonaktifkan",
    activateUser: "Aktifkan",
    confirmDeleteUser: "Apakah Anda yakin ingin menghapus pengguna ini?",
    changePin: "Ubah PIN",
    savePin: "Simpan PIN",
    /* misc */
    language: "English",
    greatJob: "Kerja bagus!",
    back: "Kembali",
    DAMAGED_ITEM: "Barang Rusak",
    MISSING_ITEM: "Barang Hilang",
    REPRINT_LABEL: "Cetak Ulang Label",
    CUSTOMER_REQUEST: "Permintaan Pelanggan",
    SPLIT_SHIPMENT: "Pengiriman Terpisah",
    OUT_OF_CONSUMABLES: "Kehabisan Bahan Kemas",
    ORDER_PROBLEM: "Masalah Order", OTHER: "Lainnya",
    BOX_SMALL: "Kardus – Kecil",
    BOX_MEDIUM: "Kardus – Sedang",
    BOX_LARGE: "Kardus – Besar",
    BUBBLE_WRAP: "Bubble Wrap",
    TAPE: "Lakban",
    PLASTIC_BAG: "Kantong Plastik",
    CONSUMABLE_OTHER: "Lainnya",
  }
};

export const HOLD_REASONS = [
  'DAMAGED_ITEM', 'MISSING_ITEM', 'REPRINT_LABEL', 'CUSTOMER_REQUEST',
  'SPLIT_SHIPMENT', 'OUT_OF_CONSUMABLES', 'ORDER_PROBLEM', 'OTHER'
];

export const CONSUMABLE_TYPES = [
  'BOX_SMALL', 'BOX_MEDIUM', 'BOX_LARGE', 'BUBBLE_WRAP', 'TAPE', 'PLASTIC_BAG', 'OTHER'
];
